name: Screenshot tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  screenshot-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install st-graphics dependencies
        run: |
          sudo apt update
          sudo apt install -y libimlib2-dev libx11-dev zlib1g-dev libfreetype-dev libfontconfig-dev libxft-dev

      - name: Clone st-graphics
        run: |
          git clone https://github.com/sergei-grechanik/st-graphics.git

      - name: Build st-graphics
        run: |
          cd st-graphics
          make

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.13"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run screenshot tests
        uses: coactions/setup-xvfb@v1
        with:
          run: |
            ./st-graphics/st -e sh -c 'uv run python -m tupimage.testing.cli run -o runlogs 2> errors.txt'

      - name: Keep the report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: runlogs
          path: ./runlogs/

      - name: Keep the errors
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: errors
          path: errors.txt
