name: Python tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_call:

permissions:
  contents: read

jobs:
  python-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.12"
          - "3.13"
          - "3.14"

    steps:
      - uses: actions/checkout@v4

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync

      - name: Check formatting with black
        run: |
          uv run black --check --diff .

      - name: Type check with mypy
        run: uv run mypy .

      - name: Run tests
        run: uv run pytest tests
