name: Screenshot tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_call:

permissions:
  contents: read

jobs:
  screenshot-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install st-graphics dependencies
        run: |
          sudo apt update
          sudo apt install -y libimlib2-dev libx11-dev zlib1g-dev libfreetype-dev libfontconfig-dev libxft-dev

      - name: Clone and build st-graphics
        run: |
          git clone https://github.com/sergei-grechanik/st-graphics.git
          cd st-graphics
          make

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.13"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run cli output tests
        uses: coactions/setup-xvfb@v1.0.1
        with:
          run: |
            ./st-graphics/st -e ./test_scripts/run-cli-tests.sh
            test_scripts/compare-cli-test.sh cli-test-outputs

      - name: Keep the cli test outputs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cli-test-outputs
          path: cli-test-outputs/

      - name: Run screenshot tests
        uses: coactions/setup-xvfb@v1.0.1
        with:
          run: |
            sudo apt install -y bsdutils imagemagick xdotool
            mkdir report
            ./st-graphics/st -e script -e -c ./test_scripts/run-screenshot-tests.sh
            cp typescript report/

      - name: Dump the tail of the output
        if: always()
        run: |
          echo "=== Last 100 lines of the typescript ==="
          tail -100 typescript || true
          echo
          echo "=== The contents of report/screenshots ==="
          ls -l report/screenshots || true

      - name: Verify the screenshots and create a report
        if: always()
        run: |
          git clone https://github.com/sergei-grechanik/terminal-reference-screenshots.git
          cp -r terminal-reference-screenshots/st/ report/
          cd report
          uv run python -m ikup.testing.cli compare screenshots/ st/ -o report.html

      - name: Keep the report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: ./report/

      # - name: Setup tmate session
      #   if: always()
      #   uses: mxschmitt/action-tmate@v3

